name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Pin npm
        run: npm i -g npm@11.6.2

      - name: Check npm version
        run: npm -v

      - name: Check npm registry config
        run: |
          npm config get registry
          npm config list -l | grep registry

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release
